server {
    listen 80;
    server_name distritogourmet.local;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name mysql.local;

    location / {
        proxy_pass http://192.168.0.232:8000/adminer.php;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
